package com.keyforge.nativeiiq.mapper;

import com.keyforge.nativeiiq.model.NativeWorkflowRow;
import com.keyforge.nativeiiq.wire.JsonSafe;
import sailpoint.object.*;
import java.time.Instant;
import java.util.*; import java.util.regex.Pattern;

/** Materializes static Workflow declarations only; never evaluates a Rule or Script. */
public final class NativeWorkflowMapper {
 private static final Pattern SECRET=Pattern.compile("(?im)(password|passwd|secret|token|credential|private[_ -]?key|client[_ -]?secret)(\\s*[=:]\\s*)(?:\"[^\"\\r\\n]*\"|'[^'\\r\\n]*'|[^\\r\\n]*)");
 private static final Pattern PRIVATE_KEY=Pattern.compile("(?s)-----BEGIN [^-]*PRIVATE KEY-----.*?-----END [^-]*PRIVATE KEY-----");
 private NativeWorkflowMapper(){}
 public static NativeWorkflowRow map(Workflow w,String system,String runId){
  NativeWorkflowRow r=new NativeWorkflowRow(); r.setSourceId(w.getId()); r.setName(w.getName()); r.setType(w.getType());
  r.setHandler(w.getHandler()); r.setDescription(w.getDescription()); r.setTaskType(w.getTaskType()==null?null:w.getTaskType().toString());
  r.setCreated(date(w.getCreated())); r.setModified(date(w.getModified())); r.setExtractedAt(Instant.now()); r.setSrcSystem(system); r.setExtractionRunId(runId);
  Map<String,Object>d=r.getDefinition(); d.put("template",w.isTemplate()); d.put("monitored",w.isMonitored()); d.put("explicitTransitions",w.isExplicitTransitions());
  d.put("configForm",w.getConfigForm()); d.put("libraries",w.getLibraries()); d.put("workItemRenderer",w.getWorkItemRenderer());
  d.put("variables",variables(w.getVariableDefinitions())); d.put("ruleLibraries",rules(w.getRuleLibraries()));
  d.put("workItemConfig",workItemConfig(w.getWorkItemConfig()));
  List<Object>steps=new ArrayList<>(); if(w.getSteps()!=null) for(Workflow.Step s:w.getSteps()) if(s!=null) steps.add(step(s)); d.put("steps",steps);
  return r;
 }
 private static Map<String,Object> step(Workflow.Step s){ Map<String,Object>m=new LinkedHashMap<>(); m.put("id",s.getId());m.put("name",s.getName());m.put("description",s.getDescription());m.put("action",s.getAction());m.put("condition",s.getCondition());m.put("conditionScript",script(s.getConditionScript()));m.put("conditionSource",scriptlet(s.getConditionSource()));m.put("actionSource",scriptlet(s.getActionSource()));m.put("script",script(s.getScript()));m.put("subProcess",ref(s.getSubProcess()));m.put("configForm",s.getConfigForm());m.put("resultVariable",s.getResultVariable());m.put("wait",s.getWait());m.put("waitSource",scriptlet(s.getWaitSource()));m.put("catches",s.getCatches());m.put("background",s.isBackground());m.put("hidden",s.isHidden());m.put("monitored",s.isMonitored());m.put("args",args(s.getArgs()));m.put("returns",returns(s.getReturns()));List<Object>tr=new ArrayList<>();if(s.getTransitions()!=null)for(Workflow.Transition t:s.getTransitions()){Map<String,Object>x=new LinkedHashMap<>();x.put("to",t.getTo());x.put("when",t.getWhen());x.put("unconditional",t.isUnconditional());x.put("script",script(t.getScript()));x.put("toSource",scriptlet(t.getToSource()));x.put("whenSource",scriptlet(t.getWhenSource()));tr.add(x);}m.put("transitions",tr);m.put("approval",approval(s.getApproval(),0,Collections.newSetFromMap(new IdentityHashMap<Workflow.Approval,Boolean>())));return m; }
 private static Map<String,Object> approval(Workflow.Approval a,int depth,Set<Workflow.Approval>seen){if(a==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("name",a.getName());m.put("description",a.getDescription());m.put("renderer",a.getRenderer());m.put("mode",a.getMode());m.put("modeScript",script(a.getModeScript()));m.put("modeSource",scriptlet(a.getModeSource()));m.put("owner",a.getOwner());m.put("originalOwner",a.getOriginalOwner());m.put("ownerScript",script(a.getOwnerScript()));m.put("ownerSource",scriptlet(a.getOwnerSource()));m.put("validation",a.getValidation());m.put("validationScript",script(a.getValidationScript()));m.put("validationSource",scriptlet(a.getValidationSource()));m.put("form",ref(a.getForm()));m.put("validator",a.getValidator());m.put("validatorScript",script(a.getValidatorScript()));m.put("send",a.getSendList());m.put("returns",returns(a.getReturns()));m.put("afterScript",script(a.getAfterScript()));m.put("interceptorScript",script(a.getInterceptorScript()));m.put("monitored",a.isMonitored());m.put("archive",a.isArchive());m.put("parallel",a.isParallel());m.put("any",a.isAny());m.put("poll",a.isPoll());m.put("parentName",a.getParent()==null?null:a.getParent().getName());m.put("workItemConfig",workItemConfig(a.getWorkItemConfig()));m.put("args",args(a.getArgs()));m.put("variables",safeMap(a.getVariables()));List<Object>children=new ArrayList<>();if(seen.add(a)&&depth<16&&a.getChildren()!=null)for(Workflow.Approval c:a.getChildren())children.add(approval(c,depth+1,seen));m.put("children",children);m.put("childrenTruncated",depth>=16);return m;}
 private static Map<String,Object> workItemConfig(WorkItemConfig c){if(c==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("name",c.getName());m.put("noWorkItem",c.isNoWorkItem());m.put("descriptionTemplate",redact(c.getDescriptionTemplate()));m.put("escalationStyle",c.getEscalationStyle());m.put("hoursTillEscalation",c.getHoursTillEscalation());m.put("hoursBetweenReminders",c.getHoursBetweenReminders());m.put("maxReminders",c.getMaxReminders());m.put("ownerRule",rule(c.getOwnerRule()));m.put("escalationRule",rule(c.getEscalationRule()));m.put("notificationEmail",ref(c.getNotificationEmail()));m.put("reminderEmail",ref(c.getReminderEmail()));m.put("escalationEmail",ref(c.getEscalationEmail()));m.put("parent",ref(c.getParent()));List<Object>owners=new ArrayList<>();if(c.getOwners()!=null)for(Identity i:c.getOwners())if(i!=null){Map<String,Object>x=new LinkedHashMap<>();x.put("id",i.getId());x.put("name",i.getName());x.put("workgroup",i.isWorkgroup());owners.add(x);}m.put("owners",owners);return m;}
 private static List<Object> returns(List<Workflow.Return> values){List<Object>out=new ArrayList<>();if(values!=null)for(Workflow.Return r:values){Map<String,Object>m=new LinkedHashMap<>();m.put("name",r.getName());m.put("to",r.getTo());m.put("merge",r.isMerge());m.put("local",r.isLocal());m.put("value",safe(r.getValue()));m.put("script",script(r.getScript()));m.put("valueSource",scriptlet(r.getValueSource()));out.add(m);}return out;}
 private static List<Object>variables(List<Workflow.Variable>vs){List<Object>out=new ArrayList<>();if(vs!=null)for(Workflow.Variable v:vs){boolean secret=sensitive(v.getName());Map<String,Object>m=new LinkedHashMap<>();m.put("name",v.getName());m.put("type",v.getType());m.put("input",v.isInput());m.put("output",v.isOutput());m.put("editable",v.isEditable());m.put("transient",v.isTransient());m.put("initializer",secret?"<redacted>":redact(v.getInitializer()));m.put("script",secret?null:script(v.getScript()));m.put("initializerSource",secret?null:scriptlet(v.getInitializerSource()));out.add(m);}return out;}
 private static List<Object>args(List<Workflow.Arg>as){List<Object>out=new ArrayList<>();if(as!=null)for(Workflow.Arg a:as){boolean secret=sensitive(a.getName());Map<String,Object>m=new LinkedHashMap<>();m.put("name",a.getName());m.put("value",secret?"<redacted>":safe(a.getValue()));m.put("literal",secret?"<redacted>":safe(a.getLiteral()));m.put("script",secret?null:script(a.getScript()));m.put("valueSource",secret?null:scriptlet(a.getValueSource()));out.add(m);}return out;}
 private static List<Object>rules(List<Rule>rs){List<Object>out=new ArrayList<>();if(rs!=null)for(Rule r:rs)out.add(rule(r));return out;}
 private static Map<String,Object>rule(Rule r){if(r==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getId());m.put("name",r.getName());m.put("type",r.getType()==null?null:r.getType().toString());m.put("language",r.getLanguage());m.put("source",source(r.getSource()));return m;}
 private static Map<String,Object>script(Script s){if(s==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("language",s.getLanguage());m.put("source",source(s.getSource()));return m;}
 private static Map<String,Object>scriptlet(Scriptlet s){if(s==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("string",safe(s.getString()));m.put("call",s.getCall());m.put("rule",s.getRule());m.put("reference",s.getReference());m.put("script",script(s.getScript()));return m;}
 private static Map<String,Object>ref(SailPointObject o){if(o==null)return null;Map<String,Object>m=new LinkedHashMap<>();m.put("id",o.getId());m.put("name",o.getName());return m;}
 private static Map<String,Object>safeMap(Map<?,?>in){Map<String,Object>out=new LinkedHashMap<>();if(in!=null)for(Map.Entry<?,?>e:in.entrySet())if(e.getKey()!=null)out.put(String.valueOf(e.getKey()),JsonSafe.toJsonSafe(e.getValue()));return out;}
 private static Object safe(Object o){Object v=JsonSafe.toJsonSafe(o);return v instanceof String?redact((String)v):v;}
 private static String redact(String s){return s==null?null:PRIVATE_KEY.matcher(SECRET.matcher(s).replaceAll("$1$2<redacted>")).replaceAll("<redacted-private-key>");}
 private static Map<String,Object> source(String raw){if(raw==null)return null;String clean=redact(raw);boolean truncated=clean.length()>12000;Map<String,Object>m=new LinkedHashMap<>();m.put("text",truncated?clean.substring(0,12000):clean);m.put("truncated",truncated);m.put("length",raw.length());try{byte[]d=java.security.MessageDigest.getInstance("SHA-256").digest(raw.getBytes(java.nio.charset.StandardCharsets.UTF_8));StringBuilder h=new StringBuilder();for(byte b:d)h.append(String.format("%02x",b&255));m.put("sha256",h.toString());}catch(Exception ignored){m.put("sha256",null);}return m;}
 private static boolean sensitive(String s){return s!=null&&s.matches("(?i).*(password|passwd|secret|token|credential|private[_ -]?key).*");}
 private static Instant date(Date d){return d==null?null:d.toInstant();}
}
