package com.keyforge.nativeiiq.source;
import com.keyforge.nativeiiq.config.NativeExtractionConfig; import com.keyforge.nativeiiq.mapper.NativeWorkflowMapper; import com.keyforge.nativeiiq.model.*;
import sailpoint.api.SailPointContext; import sailpoint.object.*; import sailpoint.tools.GeneralException; import java.time.Instant; import java.util.Iterator;
/** Read-only, deterministic, paginated native Workflow reader. */
public final class NativeWorkflowExtractor {
 private final SailPointContext context; private final NativeExtractionConfig config;
 public NativeWorkflowExtractor(SailPointContext c,NativeExtractionConfig n){context=c;config=n;}
 public NativeWorkflowExtractionResult extract(int start,int limit)throws GeneralException{QueryOptions q=new QueryOptions();q.addOrdering("name",true);q.addOrdering("id",true);if(start>0)q.setFirstRow(start);if(limit>0)q.setResultLimit(limit);NativeWorkflowExtractionResult out=new NativeWorkflowExtractionResult(config.getSourceSystem(),config.getExtractionRunId(),Instant.now());Iterator<Object[]> ids=context.search(Workflow.class,q,"id");while(ids!=null&&ids.hasNext()){String id=(String)ids.next()[0];Workflow w=context.getObjectById(Workflow.class,id);if(w==null)continue;try{NativeWorkflowRow row=NativeWorkflowMapper.map(w,config.getSourceSystem(),config.getExtractionRunId());out.getWorkflows().add(row);}finally{context.decache(w);}}attachFlowMappings(out);out.setFinishedAt(Instant.now());return out;}
 private void attachFlowMappings(NativeWorkflowExtractionResult out)throws GeneralException{Configuration cfg=context.getConfiguration();if(cfg==null||cfg.getAttributes()==null)return;for(Object key:cfg.getAttributes().keySet()){if(key==null)continue;String k=String.valueOf(key);if(!k.startsWith("workflowLCM"))continue;Object value=cfg.getAttributes().get(key);if(value==null)continue;String workflowName=String.valueOf(value);for(NativeWorkflowRow row:out.getWorkflows())if(workflowName.equals(row.getName())){Object current=row.getDefinition().get("flowConfigurationKeys");java.util.List<Object>list=current instanceof java.util.List?(java.util.List<Object>)current:new java.util.ArrayList<Object>();if(current==null)row.getDefinition().put("flowConfigurationKeys",list);list.add(k);}}}
}
