package com.keyforge.nativeload;
import com.fasterxml.jackson.databind.*;import java.time.Instant;import java.util.*;
/** Fail-loud parser for the combined role relationship envelope. */
final class NativeRoleRelationshipParser{
 private final ObjectMapper json=new ObjectMapper();
 NativeRoleRelationshipPage parse(String body){try{JsonNode root=json.readTree(body==null?"":body);if(root==null||!root.isObject())throw new NativeImportException("Native role relationships response is not an object");JsonNode err=root.get("error");if(err!=null&&!err.isNull())throw new NativeImportException("IIQ role relationship endpoint error: "+err.path("type").asText()+": "+err.path("message").asText());JsonNode e=root.get("roleEntitlements"),h=root.get("roleHierarchy");if(e==null||!e.isArray()||h==null||!h.isArray()||!root.has("returnedBundles")||!root.has("sourceCount"))throw new NativeImportException("Native role relationships response missing arrays or scan counts");List<NativeRoleRelationshipRecord>es=new ArrayList<>();for(JsonNode n:e)es.add(entitlement(n));List<NativeRoleHierarchyRecord>hs=new ArrayList<>();for(JsonNode n:h)hs.add(hierarchy(n));return new NativeRoleRelationshipPage(root.path("sourceCount").asInt(-1),root.path("returnedBundles").asInt(-1),t(root,"extractionRunId"),es,hs);}catch(NativeImportException x){throw x;}catch(Exception x){throw new NativeImportException("Invalid native role relationship JSON: "+x.getMessage(),x);}}
 private NativeRoleRelationshipRecord entitlement(JsonNode n){NativeRoleRelationshipRecord r=new NativeRoleRelationshipRecord();r.sourceBundleId=t(n,"sourceBundleId");r.roleId=t(n,"roleId");r.roleName=t(n,"roleName");r.profileOrdinal=n.path("profileOrdinal").asInt();r.constraintPath=t(n,"constraintPath");r.filterExpression=t(n,"filterExpression");JsonNode fv=n.get("filterValue");r.filterValue=fv==null||fv.isNull()?null:json.convertValue(fv,Object.class);r.entitlementType=t(n,"entitlementType");r.applicationId=t(n,"applicationId");r.application=t(n,"application");r.attributeName=t(n,"attributeName");r.attributeValue=t(n,"attributeValue");r.filterOperation=t(n,"filterOperation");r.permissionTarget=t(n,"permissionTarget");r.permissionRights=t(n,"permissionRights");r.permissionAnnotation=t(n,"permissionAnnotation");JsonNode rights=n.get("permissionRightsList");r.permissionRightsList=new ArrayList<>();if(rights!=null&&rights.isArray())for(JsonNode v:rights)if(!v.isNull())r.permissionRightsList.add(v.asText());r.srcNaturalKey=t(n,"srcNaturalKey");r.sourceSystem=t(n,"sourceSystem");r.srcInterface=t(n,"srcInterface");r.srcObjectType=t(n,"srcObjectType");r.extractionRunId=t(n,"extractionRunId");r.extractedAt=instant(n,"extractedAt");return r;}
 private NativeRoleHierarchyRecord hierarchy(JsonNode n){NativeRoleHierarchyRecord r=new NativeRoleHierarchyRecord();r.sourceRoleId=t(n,"sourceRoleId");r.sourceRoleName=t(n,"sourceRoleName");r.relatedRoleId=t(n,"relatedRoleId");r.relatedRoleName=t(n,"relatedRoleName");r.relationshipType=t(n,"relationshipType");r.srcNaturalKey=t(n,"srcNaturalKey");r.sourceSystem=t(n,"sourceSystem");r.extractionRunId=t(n,"extractionRunId");r.extractedAt=instant(n,"extractedAt");return r;}
 private static String t(JsonNode n,String k){JsonNode v=n.get(k);return v==null||v.isNull()?null:v.asText();}private static Instant instant(JsonNode n,String k){String s=t(n,k);try{return s==null?null:Instant.parse(s);}catch(Exception e){return null;}}
}
